{% set name = "channelarchiver" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/channelarchiver-{{ version }}.tar.gz
  sha256: 7be9df23e0b82912205755ccb34424536390cc11f5c82cc94d2046964103564d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tzlocal

test:
  imports:
    - channelarchiver
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/RobbieClarken/channelarchiver
  summary: Python client for the EPICS Channel Archiver.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - ocefpaf
