{% set version = "1.0.0" %}

package:
  name: channelarchiver
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/channelarchiver/channelarchiver-{{ version }}.tar.gz
  sha256: 7be9df23e0b82912205755ccb34424536390cc11f5c82cc94d2046964103564d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - tzlocal
  run:
    - python
    - tzlocal

test:
  imports:
    - channelarchiver

about:
  home: https://github.com/RobbieClarken/channelarchiver
  license: MIT
  license_file: LICENSE.rst
  summary: Python client for the EPICS Channel Archiver

extra:
  recipe-maintainers:
    - licode
    - ericdill
    - tacaswell
