{% set name = "channelarchiver" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/channelarchiver-{{ version }}.tar.gz
  sha256: 7be9df23e0b82912205755ccb34424536390cc11f5c82cc94d2046964103564d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - tzlocal

test:
  imports:
    - channelarchiver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/RobbieClarken/channelarchiver
  summary: Python client for the EPICS Channel Archiver.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - ocefpaf
