{% set version = "0.0.5" %}

package:
  name: channelarchiver
  version: {{ version }}

source:
  fn: channelarchiver-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/channelarchiver/channelarchiver-{{ version }}.tar.gz
  md5: ec0c0f80af8ebfc11ec239b299182592

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - tzlocal

  run:
    - python
    - tzlocal

test:
  imports:
    - channelarchiver

about:
  home: https://github.com/RobbieClarken/channelarchiver
  license: MIT License
  summary: 'Python client for the EPICS Channel Archiver.'

extra:
  recipe-maintainers:
    - licode
    - ericdill
    - tacaswell
