travis:
  secure:
    BINSTAR_TOKEN: GTSnoLDOxVyt2HiBaX8SARVq61dIMrwEqiWUINnxUWra452Xcj8J0uA1zmYu4KwrIVwkd1771IM38mXMmEb1YxLCkm6nePs8sLqsJNBLxFcaLttdVS5xtouKG/qhHQH2G+l5sR2PeMjXdli6gm872tqW6Qplaez+u8dWlTzKnEBlx5XUHX7ObK6yws7+QzTxGLACEdf66gaFiZufJmEMWa7GeiO9ASV8WHFhUHwfZtNftk7J+rakGJT1Wo+WrSc3DT5wdFpvnoArHtY+0nUQynGRZWoHXuvT3x66ZJV2/x/qEyR6nuSradnT2pzrV3Jei/LQMW/ndz3f07BOellwnOCOf9GNYYrwqvixFT0FY5i8q5A5DouxsReyLSVb8k+dbEjfjzkHl0Ow50CFvKHPQjOBwOPOCbaZFIQb1+MEaF2hF43aJ49VHnGBbR9FoDAMtn63k7PQnc+A33GW+23rCixiw3murDfr30FqO6LlSenS2yBrRLzVabdTa00ldduqBTwGlslk838SadtxQTaxGJEWd3Ys/3ZYu7LcPO9yFVYOM1M/joC6XCUyOWR4gdVWXThYPRSamx28IJNtYpAmNpRsnsXyM19X3D6tr3R9brr+LRur+DSKTZ+IVHF+5an1NQgJD9uzG0aeQT72kWEGjh39JstfQWLkMUZh6nfMF2g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
